package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// fixtureFiles 是合成仓库的全部文件。它不复刻真实仓库，只复刻门禁要区分的每一种形状：本模块与本地 replace
// 的两个模块（一个只被 agent 用、一个只被 hub 用）、按平台进出的源文件、汇编头文件、生成文件（agent 直接
// 引用的、只经 proto import 进闭包的、hub 独占的、谁都不引用的）与打包输入。Makefile 提供门禁读的两个目标，
// 输出格式与 deploy/agent.mk 的真实目标一致。
var fixtureFiles = map[string]string{
	"go.mod": `module example.com/fix

go 1.22

require (
	example.com/dep v0.0.0
	example.com/hubdep v0.0.0
)

replace example.com/dep => ./dep

replace example.com/hubdep => ./hubdep
`,
	"dep/go.mod":                        "module example.com/dep\n\ngo 1.21\n",
	"dep/dep.go":                        "package dep\n\nfunc X() int { return 1 }\n",
	"dep2/go.mod":                       "module example.com/dep\n\ngo 1.22\n",
	"dep2/dep.go":                       "package dep\n\nfunc X() int { return 2 }\n",
	"hubdep/go.mod":                     "module example.com/hubdep\n\ngo 1.22\n",
	"hubdep/hubdep.go":                  "package hubdep\n\nfunc Y() int { return 1 }\n",
	"buf.yaml":                          "version: v2\nmodules:\n  - path: proto\n",
	"proto/heron/v1/agent.proto":        "syntax = \"proto3\";\n\npackage heron.v1;\n\nimport \"heron/v1/types.proto\";\n",
	"proto/heron/v1/types.proto":        "syntax = \"proto3\";\n\npackage heron.v1;\n",
	"proto/heron/v1/admin.proto":        "syntax = \"proto3\";\n\npackage heron.v1;\n\nimport \"heron/v1/types.proto\";\n",
	"proto/heron/v1/public.proto":       "syntax = \"proto3\";\n\npackage heron.v1;\n",
	"gen/v1/agent.pb.go":                "// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: heron/v1/agent.proto\n\npackage v1\n\ntype ReportRequest struct{ M *Metrics }\n",
	"gen/v1/types.pb.go":                "// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: heron/v1/types.proto\n\npackage v1\n\ntype Metrics struct{}\n",
	"gen/v1/admin.pb.go":                "// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: heron/v1/admin.proto\n\npackage v1\n\ntype AdminRequest struct{ M *Metrics }\n",
	"gen/v1/public.pb.go":               "// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: heron/v1/public.proto\n\npackage v1\n\ntype PublicThing struct{}\n",
	"gen/v1/v1connect/agent.connect.go": "// Code generated by protoc-gen-connect-go. DO NOT EDIT.\n//\n// Source: heron/v1/agent.proto\n\npackage v1connect\n\nimport v1 \"example.com/fix/gen/v1\"\n\nfunc NewAgentServiceClient() *v1.ReportRequest { return nil }\n",
	"gen/v1/v1connect/admin.connect.go": "// Code generated by protoc-gen-connect-go. DO NOT EDIT.\n//\n// Source: heron/v1/admin.proto\n\npackage v1connect\n\nimport v1 \"example.com/fix/gen/v1\"\n\nfunc NewAdminServiceClient() *v1.AdminRequest { return nil }\n",
	"internal/agentlib/lib.go":          "package agentlib\n\nimport \"example.com/dep\"\n\nfunc Run() int { return dep.X() }\n",
	"internal/agentlib/lib_darwin.go":   "//go:build darwin\n\npackage agentlib\n\nfunc darwinOnly() int { return 0 }\n",
	"internal/agentlib/asm_amd64.s":     "#include \"defs.h\"\n",
	"internal/agentlib/defs.h":          "#define AGENTLIB 1\n",
	"cmd/updater/main_arm.go":           "//go:build arm\n\npackage main\n\nfunc armOnly() int { return 0 }\n",
	"cmd/agent/main.go": `package main

import (
	v1 "example.com/fix/gen/v1"
	"example.com/fix/gen/v1/v1connect"
	"example.com/fix/internal/agentlib"
)

func main() {
	_ = v1.ReportRequest{}
	_ = v1connect.NewAgentServiceClient()
	_ = agentlib.Run()
}
`,
	"cmd/updater/main.go": "package main\n\nimport \"example.com/fix/internal/agentlib\"\n\nfunc main() { _ = agentlib.Run() }\n",
	"cmd/hub/main.go": `package main

import (
	v1 "example.com/fix/gen/v1"
	"example.com/fix/gen/v1/v1connect"
	"example.com/hubdep"
)

func main() {
	_ = v1.AdminRequest{}
	_ = v1connect.NewAdminServiceClient()
	_ = hubdep.Y()
}
`,
	"deploy/agent.mk":      "AGENT_BUNDLE := 1\n",
	"deploy/agent.service": "[Service]\n",
	"deploy/hub.service":   "[Service]\n",
	"Makefile":             "agent-bundle-inputs:\n\t@printf '%s\\n' deploy/agent.mk deploy/agent.service\nagent-go-targets:\n\t@printf '%s\\n' './cmd/agent linux amd64' './cmd/agent darwin arm64' './cmd/updater linux arm 7'\n",
}

// newFixture 在临时目录里建出合成仓库、提交并打 tag v1.0.0，返回仓库根。mutate 非 nil 时在提交之前调用，
// 用来造出"基点就带某种写法"的变体。测试环境把 go 圈死在本地：-mod=mod 就地解析模块图，GOTOOLCHAIN=local
// 不下载工具链，GOPROXY=off 不碰网络，GOWORK=off 不受外层 workspace 影响。
func newFixture(t *testing.T, mutate func(dir string)) string {
	t.Helper()
	t.Setenv("GOFLAGS", "-mod=mod")
	t.Setenv("GOTOOLCHAIN", "local")
	t.Setenv("GOPROXY", "off")
	t.Setenv("GOWORK", "off")
	// 仓库放在 t.TempDir() 的子目录里：它的父目录仍是本次测试的临时目录，"替换到仓库外"的变体可以写在
	// 那里并随测试一起清理。
	dir := filepath.Join(t.TempDir(), "fix")
	for path, content := range fixtureFiles {
		writeFile(t, dir, path, content)
	}
	if mutate != nil {
		mutate(dir)
	}
	runGit(t, dir, "init", "-q")
	// 合成仓库一次性全量入库：这里提交的是夹具自身，不是任何真实仓库的工作成果。
	runGit(t, dir, "add", "-A")
	runGit(t, dir, "-c", "user.name=t", "-c", "user.email=t@example.com", "commit", "-q", "-m", "init")
	runGit(t, dir, "tag", "v1.0.0")
	return dir
}

func writeFile(t *testing.T, dir, path, content string) {
	t.Helper()
	full := filepath.Join(dir, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// appendLine 在文件末尾加一行：足以改变内容，又不动任何语法（注释或纯文本行）。
func appendLine(t *testing.T, dir, path, line string) {
	t.Helper()
	f, err := os.OpenFile(filepath.Join(dir, filepath.FromSlash(path)), os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	defer f.Close()
	if _, err := fmt.Fprintln(f, line); err != nil {
		t.Fatal(err)
	}
}

func replaceInFile(t *testing.T, dir, path, old, repl string) {
	t.Helper()
	full := filepath.Join(dir, filepath.FromSlash(path))
	b, err := os.ReadFile(full)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(b), old) {
		t.Fatalf("%s does not contain %q", path, old)
	}
	if err := os.WriteFile(full, []byte(strings.Replace(string(b), old, repl, 1)), 0o644); err != nil {
		t.Fatal(err)
	}
}

func runGit(t *testing.T, dir string, args ...string) string {
	t.Helper()
	var out bytes.Buffer
	cmd := exec.Command("git", append([]string{"-C", dir}, args...)...)
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		t.Fatalf("git %s in %s: %v\n%s", strings.Join(args, " "), dir, err, out.String())
	}
	return out.String()
}

// runTool 在 dir 上跑 run，返回退出码与合并的输出。
func runTool(t *testing.T, dir string, args ...string) (int, string) {
	t.Helper()
	var out strings.Builder
	code := run(args, dir, &out, &out)
	return code, out.String()
}

func check(t *testing.T, code int, out string, wantCode int, wantHas string) {
	t.Helper()
	if code != wantCode || (wantHas != "" && !strings.Contains(out, wantHas)) {
		t.Fatalf("run = %d (want %d), output:\n%s", code, wantCode, out)
	}
}

func TestUnchanged(t *testing.T) {
	dir := newFixture(t, nil)
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 0, "unchanged since v1.0.0")
}

func TestHubOnlyChangeIsNotAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "cmd/hub/main.go", "// changed")
	appendLine(t, dir, "deploy/hub.service", "[X-Changed]")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 0, "")
}

func TestAdminOnlyGeneratedChangeIsNotAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "gen/v1/admin.pb.go", "// changed")
	appendLine(t, dir, "gen/v1/v1connect/admin.connect.go", "// changed")
	appendLine(t, dir, "proto/heron/v1/admin.proto", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 0, "")
}

func TestImportedProtoChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "gen/v1/types.pb.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "gen/v1/types.pb.go")
}

func TestAgentGeneratedChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "gen/v1/agent.pb.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "gen/v1/agent.pb.go")
}

func TestDarwinOnlyFileChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "internal/agentlib/lib_darwin.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "internal/agentlib/lib_darwin.go")
}

func TestUpdaterRootIsCovered(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "cmd/updater/main.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "cmd/updater/main.go")
}

func TestUpdaterArmOnlyFileIsCovered(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "cmd/updater/main_arm.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "cmd/updater/main_arm.go")
}

func TestAssemblyHeaderChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "internal/agentlib/defs.h", "#define AGENTLIB_CHANGED 1")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "internal/agentlib/defs.h")
}

func TestLocalReplacementSourceChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "dep/dep.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "dep/dep.go")
}

func TestLocalReplacementGoDirectiveIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	replaceInFile(t, dir, "dep/go.mod", "go 1.21", "go 1.22")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "dep/go.mod")
}

func TestHubReplacementGoModIsNotAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	replaceInFile(t, dir, "hubdep/go.mod", "go 1.22", "go 1.23")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 0, "")
}

func TestGodebugDirectiveIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "go.mod", "godebug default=go1.21")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "godebug")
}

func TestHubOnlyRequireIsNotAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	writeFile(t, dir, "hubdep2/go.mod", fixtureFiles["hubdep/go.mod"])
	writeFile(t, dir, "hubdep2/hubdep.go", fixtureFiles["hubdep/hubdep.go"])
	replaceInFile(t, dir, "go.mod", "replace example.com/hubdep => ./hubdep", "replace example.com/hubdep => ./hubdep2")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 0, "")
}

func TestBundleFileChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "deploy/agent.service", "[X-Changed]")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "deploy/agent.service")
}

func TestFragmentChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "deploy/agent.mk", "# changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "deploy/agent.mk")
}

func TestUntrackedAgentFileIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	writeFile(t, dir, "internal/agentlib/extra.go", "package agentlib\n")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "internal/agentlib/extra.go")
}

func TestDeletedAgentFileIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	if err := os.Remove(filepath.Join(dir, "internal/agentlib/lib_darwin.go")); err != nil {
		t.Fatal(err)
	}
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "internal/agentlib/lib_darwin.go")
}

func TestAgentDependencyChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	replaceInFile(t, dir, "go.mod", "replace example.com/dep => ./dep", "replace example.com/dep => ./dep2")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "example.com/dep")
}

func TestHubDependencyChangeIsNotAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	appendLine(t, dir, "hubdep/hubdep.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 0, "")
}

func TestLocalReplacementOutsideRepositoryIsAnError(t *testing.T) {
	dir := newFixture(t, func(d string) {
		// 替换目标写在仓库外（同一临时目录树的另一个子目录）：没有可绑定的版本，基点上也取不到内容。
		writeFile(t, d, "../outside-dep/go.mod", fixtureFiles["dep/go.mod"])
		writeFile(t, d, "../outside-dep/dep.go", fixtureFiles["dep/dep.go"])
		replaceInFile(t, d, "go.mod", "replace example.com/dep => ./dep", "replace example.com/dep => ../outside-dep")
	})
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 2, "outside the repository")
}

func TestGoDirectiveChangeIsAnAgentInput(t *testing.T) {
	dir := newFixture(t, nil)
	replaceInFile(t, dir, "go.mod", "go 1.22", "go 1.22.1")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "go 1.22.1")
}

func TestReferencedGeneratedFileOutsideAgentProtoIsAnInput(t *testing.T) {
	// 基点的 agent 代码就引用了 public.pb.go 的标识符：根按引用取，而不是固定 agent.proto 一个根。
	dir := newFixture(t, func(d string) {
		replaceInFile(t, d, "cmd/agent/main.go",
			"\t_ = v1connect.NewAgentServiceClient()",
			"\t_ = v1connect.NewAgentServiceClient()\n\t_ = v1.PublicThing{}")
	})
	appendLine(t, dir, "gen/v1/public.pb.go", "// changed")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 1, "gen/v1/public.pb.go")
}

func TestBasePredatingBundleDefinitionIsAnError(t *testing.T) {
	dir := newFixture(t, func(d string) {
		writeFile(t, d, "Makefile", "all:\n\t@:\n")
	})
	writeFile(t, dir, "Makefile", fixtureFiles["Makefile"])
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 2, "predates the agent bundle definition")
}

func TestDotImportOfGeneratedPackageIsAnError(t *testing.T) {
	dir := newFixture(t, nil)
	replaceInFile(t, dir, "cmd/agent/main.go", "v1 \"example.com/fix/gen/v1\"", ". \"example.com/fix/gen/v1\"")
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 2, "dot import")
}

func TestBaseWorktreeIsRemoved(t *testing.T) {
	dir := newFixture(t, nil)
	code, out := runTool(t, dir, "-base", "v1.0.0")
	check(t, code, out, 0, "unchanged since v1.0.0")
	list := runGit(t, dir, "worktree", "list", "--porcelain")
	n := 0
	for _, l := range strings.Split(list, "\n") {
		if strings.HasPrefix(l, "worktree ") {
			n++
		}
	}
	if n != 1 {
		t.Fatalf("worktree list has %d entries after run (want 1):\n%s", n, list)
	}
}
