name: ci
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: make ci
      - name: buf breaking
        if: github.event_name == 'pull_request'
        run: buf breaking --against '.git#branch=main'
